### ISSUE TITLE
Where is the 'spot' i Can Set the Colors div ?

### ISSUE THREAD

**Issue by Mil00Z** [voldemortensen/rainbow-tags#3]
Hi !
Sorry but...I don't understand which of files is the master of settings "colors-divs"... No explanation for that in your project.. :/

Thx a Lot !

**Comment by voldemortensen** [comment]
Hey @Mil00Z! I must have missed a notification email for this issue, I just barely saw this.

Currently there isn't a spot to set the colors, but that's a great feature to add! Thanks for bringing it up.

**Comment by voldemortensen** [comment]
@Mil00Z I just published a new version that allows you to customize the colors. An example in settings would be:

```javascript
{
  "rainbowTags.colors": ["#d26", "red", "rgba(100, 200, 100, 0.5)"]
}
```

Thanks again for the idea to implement this! Feel free to re-open if you have more questions.
